-- Crear tabla de puntos de instalación
CREATE TABLE public.puntos_instalacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuadrilla TEXT NOT NULL,
    sector TEXT NOT NULL,
    destino_esp TEXT,
    frente TEXT,
    nombre_punto TEXT,
    camara_ptz TEXT,
    camara_multisensor TEXT,
    altavoz_ip TEXT,
    boton_panico TEXT,
    material_base TEXT,
    metodo_anclaje TEXT,
    medio_comunicacion TEXT,
    estado_operativo TEXT,
    latitud TEXT,
    longitud TEXT,
    dia_programado TEXT,
    completado BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Crear tabla de materiales por punto
CREATE TABLE public.materiales_punto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    punto_id BIGINT REFERENCES public.puntos_instalacion(id) ON DELETE CASCADE,
    item TEXT NOT NULL,
    cantidad TEXT NOT NULL
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.puntos_instalacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materiales_punto ENABLE ROW LEVEL SECURITY;

-- Crear políticas para permitir lectura a todo el mundo (anónimo o autenticado)
CREATE POLICY "Permitir lectura a todos en puntos" 
ON public.puntos_instalacion FOR SELECT USING (true);

CREATE POLICY "Permitir lectura a todos en materiales" 
ON public.materiales_punto FOR SELECT USING (true);

-- Crear políticas para permitir inserción/actualización SOLO a usuarios autenticados (Admin)
CREATE POLICY "Permitir actualizar puntos a usuarios autenticados" 
ON public.puntos_instalacion FOR UPDATE 
USING (auth.role() = 'authenticated');

CREATE POLICY "Permitir insertar puntos a usuarios con service_role" 
ON public.puntos_instalacion FOR INSERT 
WITH CHECK (true); -- Permitimos insert temporal para la migración

CREATE POLICY "Permitir insertar materiales a usuarios con service_role" 
ON public.materiales_punto FOR INSERT 
WITH CHECK (true); -- Permitimos insert temporal para la migración
